name: Tests (8.1)
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  code_style:
    name: Test code style
    runs-on: ubuntu-latest
    env:
      PHP_CS_FIXER_IGNORE_ENV: 1
    strategy:
      matrix:
        version: ['8.1']
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.version }}
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: composer install
      - name: Test code style
        run: composer fixer -- --dry-run
  static_analysis:
    name: Static analysis
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['8.1']
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.version }}
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: composer install
      - name: Run static analysis
        run: composer phpstan
  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['8.1']
        optional-deps: ['', 'cache/filesystem-adapter:^1.1']

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.version }}
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install Dependencies (without optional)
        if: ${{ matrix.optional-deps == '' }}
        run: composer install
      - name: Install Dependencies (with optional)
        if: ${{ matrix.optional-deps != '' }}
        run: composer require ${{ matrix.optional-deps }}
      - name: Run tests
        run: composer phpunit
